
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserTag` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model UserTag
 * 
 */
export type UserTagModel = runtime.Types.Result.DefaultSelection<Prisma.$UserTagPayload>

export type AggregateUserTag = {
  _count: UserTagCountAggregateOutputType | null
  _avg: UserTagAvgAggregateOutputType | null
  _sum: UserTagSumAggregateOutputType | null
  _min: UserTagMinAggregateOutputType | null
  _max: UserTagMaxAggregateOutputType | null
}

export type UserTagAvgAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type UserTagSumAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type UserTagMinAggregateOutputType = {
  id: number | null
  userId: number | null
  name: string | null
  content: string | null
}

export type UserTagMaxAggregateOutputType = {
  id: number | null
  userId: number | null
  name: string | null
  content: string | null
}

export type UserTagCountAggregateOutputType = {
  id: number
  userId: number
  name: number
  content: number
  _all: number
}


export type UserTagAvgAggregateInputType = {
  id?: true
  userId?: true
}

export type UserTagSumAggregateInputType = {
  id?: true
  userId?: true
}

export type UserTagMinAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  content?: true
}

export type UserTagMaxAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  content?: true
}

export type UserTagCountAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  content?: true
  _all?: true
}

export type UserTagAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserTag to aggregate.
   */
  where?: Prisma.UserTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserTags to fetch.
   */
  orderBy?: Prisma.UserTagOrderByWithRelationInput | Prisma.UserTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserTags
  **/
  _count?: true | UserTagCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserTagAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserTagSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserTagMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserTagMaxAggregateInputType
}

export type GetUserTagAggregateType<T extends UserTagAggregateArgs> = {
      [P in keyof T & keyof AggregateUserTag]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserTag[P]>
    : Prisma.GetScalarType<T[P], AggregateUserTag[P]>
}




export type UserTagGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserTagWhereInput
  orderBy?: Prisma.UserTagOrderByWithAggregationInput | Prisma.UserTagOrderByWithAggregationInput[]
  by: Prisma.UserTagScalarFieldEnum[] | Prisma.UserTagScalarFieldEnum
  having?: Prisma.UserTagScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserTagCountAggregateInputType | true
  _avg?: UserTagAvgAggregateInputType
  _sum?: UserTagSumAggregateInputType
  _min?: UserTagMinAggregateInputType
  _max?: UserTagMaxAggregateInputType
}

export type UserTagGroupByOutputType = {
  id: number
  userId: number
  name: string
  content: string
  _count: UserTagCountAggregateOutputType | null
  _avg: UserTagAvgAggregateOutputType | null
  _sum: UserTagSumAggregateOutputType | null
  _min: UserTagMinAggregateOutputType | null
  _max: UserTagMaxAggregateOutputType | null
}

type GetUserTagGroupByPayload<T extends UserTagGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserTagGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserTagGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserTagGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserTagGroupByOutputType[P]>
      }
    >
  >



export type UserTagWhereInput = {
  AND?: Prisma.UserTagWhereInput | Prisma.UserTagWhereInput[]
  OR?: Prisma.UserTagWhereInput[]
  NOT?: Prisma.UserTagWhereInput | Prisma.UserTagWhereInput[]
  id?: Prisma.IntFilter<"UserTag"> | number
  userId?: Prisma.IntFilter<"UserTag"> | number
  name?: Prisma.StringFilter<"UserTag"> | string
  content?: Prisma.StringFilter<"UserTag"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UserTagOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  content?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type UserTagWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.UserTagWhereInput | Prisma.UserTagWhereInput[]
  OR?: Prisma.UserTagWhereInput[]
  NOT?: Prisma.UserTagWhereInput | Prisma.UserTagWhereInput[]
  userId?: Prisma.IntFilter<"UserTag"> | number
  name?: Prisma.StringFilter<"UserTag"> | string
  content?: Prisma.StringFilter<"UserTag"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type UserTagOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  content?: Prisma.SortOrder
  _count?: Prisma.UserTagCountOrderByAggregateInput
  _avg?: Prisma.UserTagAvgOrderByAggregateInput
  _max?: Prisma.UserTagMaxOrderByAggregateInput
  _min?: Prisma.UserTagMinOrderByAggregateInput
  _sum?: Prisma.UserTagSumOrderByAggregateInput
}

export type UserTagScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserTagScalarWhereWithAggregatesInput | Prisma.UserTagScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserTagScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserTagScalarWhereWithAggregatesInput | Prisma.UserTagScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"UserTag"> | number
  userId?: Prisma.IntWithAggregatesFilter<"UserTag"> | number
  name?: Prisma.StringWithAggregatesFilter<"UserTag"> | string
  content?: Prisma.StringWithAggregatesFilter<"UserTag"> | string
}

export type UserTagCreateInput = {
  name: string
  content: string
  user: Prisma.UserCreateNestedOneWithoutTagsInput
}

export type UserTagUncheckedCreateInput = {
  id?: number
  userId: number
  name: string
  content: string
}

export type UserTagUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutTagsNestedInput
}

export type UserTagUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserTagCreateManyInput = {
  id?: number
  userId: number
  name: string
  content: string
}

export type UserTagUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserTagUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserTagListRelationFilter = {
  every?: Prisma.UserTagWhereInput
  some?: Prisma.UserTagWhereInput
  none?: Prisma.UserTagWhereInput
}

export type UserTagOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserTagCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  content?: Prisma.SortOrder
}

export type UserTagAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type UserTagMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  content?: Prisma.SortOrder
}

export type UserTagMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  content?: Prisma.SortOrder
}

export type UserTagSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type UserTagCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserTagCreateWithoutUserInput, Prisma.UserTagUncheckedCreateWithoutUserInput> | Prisma.UserTagCreateWithoutUserInput[] | Prisma.UserTagUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserTagCreateOrConnectWithoutUserInput | Prisma.UserTagCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserTagCreateManyUserInputEnvelope
  connect?: Prisma.UserTagWhereUniqueInput | Prisma.UserTagWhereUniqueInput[]
}

export type UserTagUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserTagCreateWithoutUserInput, Prisma.UserTagUncheckedCreateWithoutUserInput> | Prisma.UserTagCreateWithoutUserInput[] | Prisma.UserTagUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserTagCreateOrConnectWithoutUserInput | Prisma.UserTagCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserTagCreateManyUserInputEnvelope
  connect?: Prisma.UserTagWhereUniqueInput | Prisma.UserTagWhereUniqueInput[]
}

export type UserTagUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserTagCreateWithoutUserInput, Prisma.UserTagUncheckedCreateWithoutUserInput> | Prisma.UserTagCreateWithoutUserInput[] | Prisma.UserTagUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserTagCreateOrConnectWithoutUserInput | Prisma.UserTagCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserTagUpsertWithWhereUniqueWithoutUserInput | Prisma.UserTagUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserTagCreateManyUserInputEnvelope
  set?: Prisma.UserTagWhereUniqueInput | Prisma.UserTagWhereUniqueInput[]
  disconnect?: Prisma.UserTagWhereUniqueInput | Prisma.UserTagWhereUniqueInput[]
  delete?: Prisma.UserTagWhereUniqueInput | Prisma.UserTagWhereUniqueInput[]
  connect?: Prisma.UserTagWhereUniqueInput | Prisma.UserTagWhereUniqueInput[]
  update?: Prisma.UserTagUpdateWithWhereUniqueWithoutUserInput | Prisma.UserTagUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserTagUpdateManyWithWhereWithoutUserInput | Prisma.UserTagUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserTagScalarWhereInput | Prisma.UserTagScalarWhereInput[]
}

export type UserTagUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserTagCreateWithoutUserInput, Prisma.UserTagUncheckedCreateWithoutUserInput> | Prisma.UserTagCreateWithoutUserInput[] | Prisma.UserTagUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserTagCreateOrConnectWithoutUserInput | Prisma.UserTagCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserTagUpsertWithWhereUniqueWithoutUserInput | Prisma.UserTagUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserTagCreateManyUserInputEnvelope
  set?: Prisma.UserTagWhereUniqueInput | Prisma.UserTagWhereUniqueInput[]
  disconnect?: Prisma.UserTagWhereUniqueInput | Prisma.UserTagWhereUniqueInput[]
  delete?: Prisma.UserTagWhereUniqueInput | Prisma.UserTagWhereUniqueInput[]
  connect?: Prisma.UserTagWhereUniqueInput | Prisma.UserTagWhereUniqueInput[]
  update?: Prisma.UserTagUpdateWithWhereUniqueWithoutUserInput | Prisma.UserTagUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserTagUpdateManyWithWhereWithoutUserInput | Prisma.UserTagUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserTagScalarWhereInput | Prisma.UserTagScalarWhereInput[]
}

export type UserTagCreateWithoutUserInput = {
  name: string
  content: string
}

export type UserTagUncheckedCreateWithoutUserInput = {
  id?: number
  name: string
  content: string
}

export type UserTagCreateOrConnectWithoutUserInput = {
  where: Prisma.UserTagWhereUniqueInput
  create: Prisma.XOR<Prisma.UserTagCreateWithoutUserInput, Prisma.UserTagUncheckedCreateWithoutUserInput>
}

export type UserTagCreateManyUserInputEnvelope = {
  data: Prisma.UserTagCreateManyUserInput | Prisma.UserTagCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserTagUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserTagWhereUniqueInput
  update: Prisma.XOR<Prisma.UserTagUpdateWithoutUserInput, Prisma.UserTagUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserTagCreateWithoutUserInput, Prisma.UserTagUncheckedCreateWithoutUserInput>
}

export type UserTagUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserTagWhereUniqueInput
  data: Prisma.XOR<Prisma.UserTagUpdateWithoutUserInput, Prisma.UserTagUncheckedUpdateWithoutUserInput>
}

export type UserTagUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserTagScalarWhereInput
  data: Prisma.XOR<Prisma.UserTagUpdateManyMutationInput, Prisma.UserTagUncheckedUpdateManyWithoutUserInput>
}

export type UserTagScalarWhereInput = {
  AND?: Prisma.UserTagScalarWhereInput | Prisma.UserTagScalarWhereInput[]
  OR?: Prisma.UserTagScalarWhereInput[]
  NOT?: Prisma.UserTagScalarWhereInput | Prisma.UserTagScalarWhereInput[]
  id?: Prisma.IntFilter<"UserTag"> | number
  userId?: Prisma.IntFilter<"UserTag"> | number
  name?: Prisma.StringFilter<"UserTag"> | string
  content?: Prisma.StringFilter<"UserTag"> | string
}

export type UserTagCreateManyUserInput = {
  id?: number
  name: string
  content: string
}

export type UserTagUpdateWithoutUserInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserTagUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserTagUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}



export type UserTagSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  name?: boolean
  content?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userTag"]>

export type UserTagSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  name?: boolean
  content?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userTag"]>

export type UserTagSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  name?: boolean
  content?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userTag"]>

export type UserTagSelectScalar = {
  id?: boolean
  userId?: boolean
  name?: boolean
  content?: boolean
}

export type UserTagOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "name" | "content", ExtArgs["result"]["userTag"]>
export type UserTagInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserTagIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserTagIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UserTagPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserTag"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: number
    name: string
    content: string
  }, ExtArgs["result"]["userTag"]>
  composites: {}
}

export type UserTagGetPayload<S extends boolean | null | undefined | UserTagDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserTagPayload, S>

export type UserTagCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserTagFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserTagCountAggregateInputType | true
  }

export interface UserTagDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserTag'], meta: { name: 'UserTag' } }
  /**
   * Find zero or one UserTag that matches the filter.
   * @param {UserTagFindUniqueArgs} args - Arguments to find a UserTag
   * @example
   * // Get one UserTag
   * const userTag = await prisma.userTag.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserTagFindUniqueArgs>(args: Prisma.SelectSubset<T, UserTagFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserTagClient<runtime.Types.Result.GetResult<Prisma.$UserTagPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserTag that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserTagFindUniqueOrThrowArgs} args - Arguments to find a UserTag
   * @example
   * // Get one UserTag
   * const userTag = await prisma.userTag.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserTagFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserTagFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserTagClient<runtime.Types.Result.GetResult<Prisma.$UserTagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserTag that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserTagFindFirstArgs} args - Arguments to find a UserTag
   * @example
   * // Get one UserTag
   * const userTag = await prisma.userTag.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserTagFindFirstArgs>(args?: Prisma.SelectSubset<T, UserTagFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserTagClient<runtime.Types.Result.GetResult<Prisma.$UserTagPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserTag that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserTagFindFirstOrThrowArgs} args - Arguments to find a UserTag
   * @example
   * // Get one UserTag
   * const userTag = await prisma.userTag.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserTagFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserTagFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserTagClient<runtime.Types.Result.GetResult<Prisma.$UserTagPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserTags that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserTagFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserTags
   * const userTags = await prisma.userTag.findMany()
   * 
   * // Get first 10 UserTags
   * const userTags = await prisma.userTag.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userTagWithIdOnly = await prisma.userTag.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserTagFindManyArgs>(args?: Prisma.SelectSubset<T, UserTagFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserTagPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserTag.
   * @param {UserTagCreateArgs} args - Arguments to create a UserTag.
   * @example
   * // Create one UserTag
   * const UserTag = await prisma.userTag.create({
   *   data: {
   *     // ... data to create a UserTag
   *   }
   * })
   * 
   */
  create<T extends UserTagCreateArgs>(args: Prisma.SelectSubset<T, UserTagCreateArgs<ExtArgs>>): Prisma.Prisma__UserTagClient<runtime.Types.Result.GetResult<Prisma.$UserTagPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserTags.
   * @param {UserTagCreateManyArgs} args - Arguments to create many UserTags.
   * @example
   * // Create many UserTags
   * const userTag = await prisma.userTag.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserTagCreateManyArgs>(args?: Prisma.SelectSubset<T, UserTagCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserTags and returns the data saved in the database.
   * @param {UserTagCreateManyAndReturnArgs} args - Arguments to create many UserTags.
   * @example
   * // Create many UserTags
   * const userTag = await prisma.userTag.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserTags and only return the `id`
   * const userTagWithIdOnly = await prisma.userTag.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserTagCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserTagCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserTagPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserTag.
   * @param {UserTagDeleteArgs} args - Arguments to delete one UserTag.
   * @example
   * // Delete one UserTag
   * const UserTag = await prisma.userTag.delete({
   *   where: {
   *     // ... filter to delete one UserTag
   *   }
   * })
   * 
   */
  delete<T extends UserTagDeleteArgs>(args: Prisma.SelectSubset<T, UserTagDeleteArgs<ExtArgs>>): Prisma.Prisma__UserTagClient<runtime.Types.Result.GetResult<Prisma.$UserTagPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserTag.
   * @param {UserTagUpdateArgs} args - Arguments to update one UserTag.
   * @example
   * // Update one UserTag
   * const userTag = await prisma.userTag.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserTagUpdateArgs>(args: Prisma.SelectSubset<T, UserTagUpdateArgs<ExtArgs>>): Prisma.Prisma__UserTagClient<runtime.Types.Result.GetResult<Prisma.$UserTagPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserTags.
   * @param {UserTagDeleteManyArgs} args - Arguments to filter UserTags to delete.
   * @example
   * // Delete a few UserTags
   * const { count } = await prisma.userTag.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserTagDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserTagDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserTagUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserTags
   * const userTag = await prisma.userTag.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserTagUpdateManyArgs>(args: Prisma.SelectSubset<T, UserTagUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserTags and returns the data updated in the database.
   * @param {UserTagUpdateManyAndReturnArgs} args - Arguments to update many UserTags.
   * @example
   * // Update many UserTags
   * const userTag = await prisma.userTag.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserTags and only return the `id`
   * const userTagWithIdOnly = await prisma.userTag.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserTagUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserTagUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserTagPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserTag.
   * @param {UserTagUpsertArgs} args - Arguments to update or create a UserTag.
   * @example
   * // Update or create a UserTag
   * const userTag = await prisma.userTag.upsert({
   *   create: {
   *     // ... data to create a UserTag
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserTag we want to update
   *   }
   * })
   */
  upsert<T extends UserTagUpsertArgs>(args: Prisma.SelectSubset<T, UserTagUpsertArgs<ExtArgs>>): Prisma.Prisma__UserTagClient<runtime.Types.Result.GetResult<Prisma.$UserTagPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserTagCountArgs} args - Arguments to filter UserTags to count.
   * @example
   * // Count the number of UserTags
   * const count = await prisma.userTag.count({
   *   where: {
   *     // ... the filter for the UserTags we want to count
   *   }
   * })
  **/
  count<T extends UserTagCountArgs>(
    args?: Prisma.Subset<T, UserTagCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserTagCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserTagAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserTagAggregateArgs>(args: Prisma.Subset<T, UserTagAggregateArgs>): Prisma.PrismaPromise<GetUserTagAggregateType<T>>

  /**
   * Group by UserTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserTagGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserTagGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserTagGroupByArgs['orderBy'] }
      : { orderBy?: UserTagGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserTagGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserTagGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserTag model
 */
readonly fields: UserTagFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserTag.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserTagClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserTag model
 */
export interface UserTagFieldRefs {
  readonly id: Prisma.FieldRef<"UserTag", 'Int'>
  readonly userId: Prisma.FieldRef<"UserTag", 'Int'>
  readonly name: Prisma.FieldRef<"UserTag", 'String'>
  readonly content: Prisma.FieldRef<"UserTag", 'String'>
}
    

// Custom InputTypes
/**
 * UserTag findUnique
 */
export type UserTagFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTag
   */
  select?: Prisma.UserTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTag
   */
  omit?: Prisma.UserTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTagInclude<ExtArgs> | null
  /**
   * Filter, which UserTag to fetch.
   */
  where: Prisma.UserTagWhereUniqueInput
}

/**
 * UserTag findUniqueOrThrow
 */
export type UserTagFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTag
   */
  select?: Prisma.UserTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTag
   */
  omit?: Prisma.UserTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTagInclude<ExtArgs> | null
  /**
   * Filter, which UserTag to fetch.
   */
  where: Prisma.UserTagWhereUniqueInput
}

/**
 * UserTag findFirst
 */
export type UserTagFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTag
   */
  select?: Prisma.UserTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTag
   */
  omit?: Prisma.UserTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTagInclude<ExtArgs> | null
  /**
   * Filter, which UserTag to fetch.
   */
  where?: Prisma.UserTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserTags to fetch.
   */
  orderBy?: Prisma.UserTagOrderByWithRelationInput | Prisma.UserTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserTags.
   */
  cursor?: Prisma.UserTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserTags.
   */
  distinct?: Prisma.UserTagScalarFieldEnum | Prisma.UserTagScalarFieldEnum[]
}

/**
 * UserTag findFirstOrThrow
 */
export type UserTagFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTag
   */
  select?: Prisma.UserTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTag
   */
  omit?: Prisma.UserTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTagInclude<ExtArgs> | null
  /**
   * Filter, which UserTag to fetch.
   */
  where?: Prisma.UserTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserTags to fetch.
   */
  orderBy?: Prisma.UserTagOrderByWithRelationInput | Prisma.UserTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserTags.
   */
  cursor?: Prisma.UserTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserTags.
   */
  distinct?: Prisma.UserTagScalarFieldEnum | Prisma.UserTagScalarFieldEnum[]
}

/**
 * UserTag findMany
 */
export type UserTagFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTag
   */
  select?: Prisma.UserTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTag
   */
  omit?: Prisma.UserTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTagInclude<ExtArgs> | null
  /**
   * Filter, which UserTags to fetch.
   */
  where?: Prisma.UserTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserTags to fetch.
   */
  orderBy?: Prisma.UserTagOrderByWithRelationInput | Prisma.UserTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserTags.
   */
  cursor?: Prisma.UserTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserTags.
   */
  skip?: number
  distinct?: Prisma.UserTagScalarFieldEnum | Prisma.UserTagScalarFieldEnum[]
}

/**
 * UserTag create
 */
export type UserTagCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTag
   */
  select?: Prisma.UserTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTag
   */
  omit?: Prisma.UserTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTagInclude<ExtArgs> | null
  /**
   * The data needed to create a UserTag.
   */
  data: Prisma.XOR<Prisma.UserTagCreateInput, Prisma.UserTagUncheckedCreateInput>
}

/**
 * UserTag createMany
 */
export type UserTagCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserTags.
   */
  data: Prisma.UserTagCreateManyInput | Prisma.UserTagCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserTag createManyAndReturn
 */
export type UserTagCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTag
   */
  select?: Prisma.UserTagSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserTag
   */
  omit?: Prisma.UserTagOmit<ExtArgs> | null
  /**
   * The data used to create many UserTags.
   */
  data: Prisma.UserTagCreateManyInput | Prisma.UserTagCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTagIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserTag update
 */
export type UserTagUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTag
   */
  select?: Prisma.UserTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTag
   */
  omit?: Prisma.UserTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTagInclude<ExtArgs> | null
  /**
   * The data needed to update a UserTag.
   */
  data: Prisma.XOR<Prisma.UserTagUpdateInput, Prisma.UserTagUncheckedUpdateInput>
  /**
   * Choose, which UserTag to update.
   */
  where: Prisma.UserTagWhereUniqueInput
}

/**
 * UserTag updateMany
 */
export type UserTagUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserTags.
   */
  data: Prisma.XOR<Prisma.UserTagUpdateManyMutationInput, Prisma.UserTagUncheckedUpdateManyInput>
  /**
   * Filter which UserTags to update
   */
  where?: Prisma.UserTagWhereInput
  /**
   * Limit how many UserTags to update.
   */
  limit?: number
}

/**
 * UserTag updateManyAndReturn
 */
export type UserTagUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTag
   */
  select?: Prisma.UserTagSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserTag
   */
  omit?: Prisma.UserTagOmit<ExtArgs> | null
  /**
   * The data used to update UserTags.
   */
  data: Prisma.XOR<Prisma.UserTagUpdateManyMutationInput, Prisma.UserTagUncheckedUpdateManyInput>
  /**
   * Filter which UserTags to update
   */
  where?: Prisma.UserTagWhereInput
  /**
   * Limit how many UserTags to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTagIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserTag upsert
 */
export type UserTagUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTag
   */
  select?: Prisma.UserTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTag
   */
  omit?: Prisma.UserTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTagInclude<ExtArgs> | null
  /**
   * The filter to search for the UserTag to update in case it exists.
   */
  where: Prisma.UserTagWhereUniqueInput
  /**
   * In case the UserTag found by the `where` argument doesn't exist, create a new UserTag with this data.
   */
  create: Prisma.XOR<Prisma.UserTagCreateInput, Prisma.UserTagUncheckedCreateInput>
  /**
   * In case the UserTag was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserTagUpdateInput, Prisma.UserTagUncheckedUpdateInput>
}

/**
 * UserTag delete
 */
export type UserTagDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTag
   */
  select?: Prisma.UserTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTag
   */
  omit?: Prisma.UserTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTagInclude<ExtArgs> | null
  /**
   * Filter which UserTag to delete.
   */
  where: Prisma.UserTagWhereUniqueInput
}

/**
 * UserTag deleteMany
 */
export type UserTagDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserTags to delete
   */
  where?: Prisma.UserTagWhereInput
  /**
   * Limit how many UserTags to delete.
   */
  limit?: number
}

/**
 * UserTag without action
 */
export type UserTagDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTag
   */
  select?: Prisma.UserTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTag
   */
  omit?: Prisma.UserTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTagInclude<ExtArgs> | null
}
